(defun split-str (string &optional (separator " "))
  (split-str-1 string separator))

(defun split-str-1 (string &optional (separator " ") (r nil))
  (let ((n (position separator string
		     :from-end t
		     :test #'(lambda (x y)
			       (find y x :test #'string=)))))
    (if n
	(split-str-1 (subseq string 0 n) separator (cons (subseq string (1+ n)) r))
      (cons string r))))

(setq plist (list))

(let ((in (open "patient.txt" :if-does-not-exist nil)))
	(when in
		(loop for line = (read-line in nil)
			while line do()
					
					(setq plist (append plist(list (split-str line))))
		)

		(close in)
	)
)

(defun option1 ()
	(terpri)
	(format t "~20a ~20a ~20a ~20a ~20a ~20a ~20a" "NAME" "AGE" "PATIENT_NO" "SEX" "DOCTOR" "FIRST_VISIT" "NEXT_VISIT")
	(terpri)
	(princ "----------------------------------------------------------------------------------------------------------------------------------------")
	(terpri)
	(dolist (n plist)
	 (setq pname (car n))
	 (setq pname (concatenate 'string pname " "))
	 (setq pname (concatenate 'string pname (cadr n)))
	 (setq dname (car (cdr (cddddr n))))
	 (setq dname (concatenate 'string dname " "))
	 (setq dname (concatenate 'string dname (car (cddr (cddddr n)))))
	 (format t "~20A ~20A ~20A " pname (caddr n) (cadddr n))
	 (format t "~20A ~20A ~20A ~20A" (car (cddddr n)) dname (car (cdddr (cddddr n))) (car (cddddr (cddddr n))))
	 (terpri))
)

(defun option2 ()
	(princ "Enter the name of patient : ")
	(setq name (read))
	(terpri)
	(format t "~20a ~20a ~20a ~20a ~20a ~20a ~20a" "NAME" "AGE" "PATIENT_NO" "SEX" "DOCTOR" "FIRST_VISIT" "NEXT_VISIT")
	(terpri)
	(princ "----------------------------------------------------------------------------------------------------------------------------------------")
	(terpri)
	(dolist (n plist)
	 (setq pname (car n))
	 (setq pname (concatenate 'string pname " "))
	 (setq pname (concatenate 'string pname (cadr n)))
	 (setq dname (car (cdr (cddddr n))))
	 (setq dname (concatenate 'string dname " "))
	 (setq dname (concatenate 'string dname (car (cddr (cddddr n)))))
	 (if (string= name (string-upcase (car n)))
		 (format t "~20A ~20A ~20A ~20A ~20A ~20A ~20A" pname (caddr n) (cadddr n) (car (cddddr n)) dname (car (cdddr (cddddr n))) (car (cddddr (cddddr n))))
	 )
	 (if (string= name (string-upcase (car n)))
	 	 (terpri)
	 )
	)
)

(defun option3 ()
	(princ "Enter the patient code: ")
	(setq code (read))
	(terpri)
	(format t "~20a ~20a ~20a ~20a ~20a ~20a ~20a" "NAME" "AGE" "PATIENT_NO" "SEX" "DOCTOR" "FIRST_VISIT" "NEXT_VISIT")
	(terpri)
	(princ "----------------------------------------------------------------------------------------------------------------------------------------")
	(terpri)
	(dolist (n plist)
	 (setq pname (car n))
	 (setq pname (concatenate 'string pname " "))
	 (setq pname (concatenate 'string pname (cadr n)))
	 (setq dname (car (cdr (cddddr n))))
	 (setq dname (concatenate 'string dname " "))
	 (setq dname (concatenate 'string dname (car (cddr (cddddr n)))))
	 (if (string= code (string-upcase (cadddr n)))
		 (format t "~20A ~20A ~20A ~20A ~20A ~20A ~20A" pname (caddr n) (cadddr n) (car (cddddr n)) dname (car (cdddr (cddddr n))) (car (cddddr (cddddr n))))
	 )
	 (if (string= code (string-upcase (car n)))
	 	 (terpri)
	 )
	)
)

(defun option4 ()
 
 (princ "Enter the period to search")
 (terpri)
 (princ "  - START (eg. 2017/06/01) : ")
 (setq start (read))

 (princ "  - END : (eg. 2017/12/31) : " )
 (setq end (read))
 (terpri)

 (format t "~20a ~20a ~20a ~20a ~20a ~20a ~20a" "NAME" "AGE" "PATIENT_NO" "SEX" "DOCTOR" "FIRST_VISIT" "NEXT_VISIT")
 (terpri)
 (princ "----------------------------------------------------------------------------------------------------------------------------------------")
 (terpri)
 (dolist (n plist)
	(setq pname (car n))
	(setq pname (concatenate 'string pname " "))
	(setq pname (concatenate 'string pname (cadr n)))
	(setq dname (car (cdr (cddddr n))))
	(setq dname (concatenate 'string dname " "))
	(setq dname (concatenate 'string dname (car (cddr (cddddr n)))))
	(if (and (string<= start (car (cddddr (cddddr n)))) (string> end (car (cddddr (cddddr n)))))  
	 (format t "~20A ~20A ~20A ~20A ~20A ~20A ~20A" pname (caddr n) (cadddr n) (car (cddddr n)) dname (car (cdddr (cddddr n))) (car (cddddr (cddddr n))))
	)
	(if (and (string<= start (car (cddddr (cddddr n)))) (string> end (car (cddddr (cddddr n)))))  
	 (terpri)
	)
 )
)

(terpri)(terpri)(terpri)
(princ "*********** DATABASE for SKKU SOFT HOSPITAL ***********")
(terpri)(terpri)
(princ " 1. Print every patients ")
(terpri)
(princ " 2. Search patient info BY NAME")
(terpri)
(princ " 3. Search patient info BY PATIENT_NO")
(terpri)
(princ " 4. Print reservation list")
(terpri)
(princ " 5. To exit")
(terpri)(terpri)
(princ "*******************************************************")
(terpri)(terpri)
(princ ">>  ")
(setq option (read))
(if (= option 1)
	(option1)
)
(if (= option 2)
	(option2)
)
(if (= option 3)
	(option3) 
)
(if (= option 4)
	(option4)
)
(loop 
	(if (= option 5)
		(return))
	(terpri)(terpri)(terpri)
	(princ " * 1. Print every patients ")
	(terpri)
	(princ " * 2. Search patient info BY NAME")
	(terpri)
	(princ " * 3. Search patient info BY PATIENT_NO")
	(terpri)
	(princ " * 4. Print reservation list")
	(terpri)
	(princ " * 5. To exit")
	(terpri)
	(terpri)
	(princ ">>  ")
	(setq option (read))
	(if (= option 1)
		(option1)
	)
	(if (= option 2)
		(option2)
	)
	(if (= option 3)
		(option3) 
	)
	(if (= option 4)
		(option4)
	)
)
